### ISSUE TITLE
Provide utility function set.groundhogr.folder()

### ISSUE THREAD

**Issue by Bisaloo** [Bisaloo/groundhogR#15]
This would be useful for users who don't know how to edit environment variable themselves

**Comment by urisohn** [comment]
i need more background, don't understand fully.
so you are saying, "since we will no longer use a default location but users have to set it themselves, and they may not know how to do that..."
I don't  know what a utility function would be.

but i would like a simpler approach for the majority of researchers who do not care about where stuff is saved.

i would like a menu prompt, somethign like this pops up the first time they do library('groundhogR')

"By default we will save needed files here "C://documents/etc/abc/user/" . If you are OK with that press enter, if you would like to change the folder where groundhogR saves files, type "change"

Then, if they press change, they receive instructions.

Does that address what you were raising or is this another issue?

**Comment by Bisaloo** [comment]
> but i would like a simpler approach for the majority of researchers who do not care about where stuff is saved.
>
> i would like a menu prompt, somethign like this pops up the first time they do library('groundhogR')
>
> "By default we will save needed files here "C://documents/etc/abc/user/" . If you are OK with that press enter, if you would like to change the folder where groundhogR saves files, type "change"
>
> Then, if they press change, they receive instructions.

You're describing the current approach so we agree on this! However, I'm afraid users might change their minds about the location at some point and don't know how to change it.

The idea would be to provide et `set.groundhogr.folder()` function, à la `set.wd()` to update the path where groundhogR saves files.

**Comment by urisohn** [comment]
ah, ok, yes, I like that
